### ISSUE TITLE
App freezes and causes reboot of phone

### ISSUE THREAD

**Issue by n-eq** [Oxmose/ENSIEDT#1]
I just tested (twice) the application on my personal phone and it shows some issues.
When pressing the 'Connexion' button after entering the login and password, the screen freezes and it causes the phone to reboot after a few seconds. 
I read the source code but couldn't figure out any potential source of problem. It would have been easier if I had Android Studio, which is not the case...

**Comment by Oxmose** [comment]
The crash is most likely to be caused by the SubsamplingScaleImageView component that requires API24 at least I guess. Basicaly I created the app for my phone and used GitHub to store it.
I developped this app for Android 7 but if you wish I can take a quick look to port it to earlier versions of Android.

**Comment by Oxmose** [comment]
Ho by the way, you're the first to report a reboot of the phone, usually the app just shut off. If you give me more info about your Android version it would help a lot :)

**Comment by Marrakchino** [comment]
Ha! I'm using the oldie version 4 of Android (4.1.2). It's very likely a compatibility problem I think.

**Comment by Oxmose** [comment]
Ok, if you wish you can fix the issue and ask for a pull reauest or
something.
